apiVersion: v1
kind: Secret 
metadata:
  name: environment-variables
  namespace: sony-interior 

data:
  GEMINI_API_KEY: QUl6YVN5Q0poTEFiMU1MbnhCbmpScVJnblZxZ3k5MGx5Mk93LWQwCgo=
  DATABASE_URL: cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpucGdfem4wS0Frak1MOER1QGVwLWRhcmstZnJvc3QtYWQyMjNscmctcG9vbGVyLmMtMi51cy1lYXN0LTEuYXdzLm5lb24udGVjaC9uZW9uZGI/c3NsbW9kZT1yZXF1aXJlJmNoYW5uZWxfYmluZGluZz1yZXF1aXJlCg==
  NEXT_PUBLIC_SANITY_PROJECT_ID: NWVrMm15ZzM=
  SANITY_API_TOKEN: c2tqcXdZZFFtN0xCQ3IwaTBEb1VxY25MQTk2T2IzSklVSGpwd1k2RFVHbkF4anBJSVFEVDJsWDhYZlRXNUtqODZsZUczM2RGUm56V2xlUFBNRXM2d3pHWTBUTHJiZEVtYXRteGVJa29jUFdZODVtdmlScThhVzRobmJKT2ZsVE5pSmFNOWk0T1VFY0JIcGtONDU1UmxvZVBXcGM2cmNyczdXQmJTejkwVnMyNWZORVo3eXBK
